###
GET http://localhost:3000/setup

###
GET http://localhost:3000/

###
POST http://localhost:3000/
Content-Type: application/json

{
    "name" : "james", "location" : "23 Hello World"
}